set(CMAKE_EXECUTABLE_SUFFIX ".wasm")

set(THIRD_PARTIES ${CMAKE_SOURCE_DIR}/third_parties)
set(THIRD_PARTIES_BINARIES ${CMAKE_BINARY_DIR}/third_parties)
set(GPAC_LOCATION ${THIRD_PARTIES}/gpac)
set(GPAC_BINARIES ${THIRD_PARTIES_BINARIES}/gpac)
set(FFMPEG_LOCATION ${THIRD_PARTIES}/ffmpeg)

add_compile_definitions(GPAC_HAVE_CONFIG_H GF_CONFIG_H GPAC_CONFIG_EMSCRIPTEN GPAC_DISABLE_NETWORK GPAC_HAS_MTIM_NSEC GPAC_HAS_POLL GPAC_DISABLE_REMOTERY GPAC_HAS_STRLCPY GPAC_HAS_SOCK_UN GPAC_HAS_IPV6)

set(FILTERS_JSON_DESC "")

macro(add_filter FILTERNAME ENTRYFILES LINKFILES ENTRY_FN DEFINITIONS INCLUDES LINK_FLAGS VERSION)
        list(APPEND WASM_FILES ${CMAKE_BINARY_DIR}/${FILTERNAME}.wasm)

        add_executable(${FILTERNAME}_${VERSION} ${ENTRYFILES})

        target_link_libraries(${FILTERNAME}_${VERSION} ${LINKFILES})

        set_target_properties(${FILTERNAME}_${VERSION}
                PROPERTIES
                LINK_FLAGS " -sWASM_BIGINT -s SIDE_MODULE=2 -s EXPORTED_FUNCTIONS=${ENTRY_FN} ${LINK_FLAGS}"
        )

        target_compile_definitions(${FILTERNAME}_${VERSION} PRIVATE ${DEFINITIONS})
        target_include_directories(${FILTERNAME}_${VERSION} PRIVATE ${INCLUDES})
        file(READ ${CMAKE_CURRENT_SOURCE_DIR}/${FILTERNAME}.json FILTER_JSON_DESC)
        list(APPEND FILTERS_JSON_DESC "\"${FILTERNAME}_${VERSION}.wasm\":${FILTER_JSON_DESC}")
endmacro()